name: Deploy Cloud

on:
  push:
    branches:
      - main

env:
  ACCESS_KEY:          ${{secrets.AWS_ACCESS_KEY_ID}}
  SECRET_ACCESS_KEY:   ${{secrets.AWS_SECRET_ACCESS_KEY}}


jobs:
  deploy:
    name: DeployCloud
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            "us-east-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "^1.3.7"
            terraform_wrapper: false
      
      - name: Deploy cloud
        id: deploy-cloud
        run: |
          cd Terraform/prod
          terraform init
          terraform apply -auto-approve -var "access_key=${{ env.ACCESS_KEY }}" -var "secret_access_key=${{ env.SECRET_ACCESS_KEY }}"